# This workflow will install Python dependencies, run tests and lint with a single version of Python
# Test 

name: Sync test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest # ${{ matrix.os }}
    #strategy:
     #   matrix:
      #      os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup Database
      uses: mirromutth/mysql-action@v1.1
      with:
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'sync' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'syncpws' # Required if "mysql user" is empty, default is empty. The root superuser password
        host port: 3889
        container port: 3889
    - name: Start Database
      run : |
        docker run --name=mysql -d mysql --publish 6603:3306
        docker ps
        sudo apt-get install mysql-client -y
        # ping -c 4 127.0.0.1 3306
        ping -c 4 127.0.0.1 6603
        mysql -usync -psyncpws -h127.0.0.1 -P6603 -e 'CREATE DATABASE sync'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Log(s)
      run: |
        cat ./log/*