# Test sync code

name: Sync test

on: [push, pull_request]

jobs:
  sync-agentless:

    runs-on: ubuntu-latest

    # Create the DB
    services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: sync
                    MYSQL_ROOT_PASSWORD: syncpws
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Install Database dependencies and test it
      run : |
        sudo apt-get install mysql-client -y
        mysql -uroot -psyncpws -h0.0.0.0 -P32768 -e "SHOW DATABASES;" # Check
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install py3 dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Log(s)
      run: |
        cat ./log/*
    - name: Print DB(s)
      run: |
        mysql -uroot -psyncpws -h0.0.0.0 -P32768 -e "SHOW TABLES FROM sync;" # Check
        mysql -uroot -psyncpws -h0.0.0.0 -P32768 -e "SELECT * FROM sync.testfile;" # Show my test table content

  sync-agent-1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        path: sync
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install py3 dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        sed -i 's/False/True/g' ./bin/test_sync.py # Change test file to make it agent
        pytest
    - name: Log(s)
      run: |
        cat ./log/*
    - name: Upload file(s)
      run: |
         mkdir -p sync/artifact
         cp -a ./flussi/cloned/. sync/artifact/
    - name: View file structure
      run: |
        sudo apt install tree
        tree

  sync-agent-2:
    needs: sync-agent-1
    runs-on: ubuntu-latest

    # Create the DB
    services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: sync
                    MYSQL_ROOT_PASSWORD: syncpws
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - name: Install Database dependencies and test it
      run : |
        sudo apt-get install mysql-client -y
        mysql -uroot -psyncpws -h0.0.0.0 -P32768 -e "SHOW DATABASES;" # Check
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install py3 dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements/requirements.txt
    - name: View file structure
      run: |
        sudo apt install tree
        tree
    - name: Download file(s)
      run: |
         cp -a sync/artifact/. ./flussi/
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Log(s)
      run: |
        cat ./log/*
    - name: Print DB(s)
      run: |
        mysql -uroot -psyncpws -h0.0.0.0 -P32768 -e "SHOW TABLES FROM sync;" # Check
        mysql -uroot -psyncpws -h0.0.0.0 -P32768 -e "SELECT * FROM sync.testfile;" # Show my test table content
